import turtle
 
turtle.right(90)
turtle.penup()
font1 = ("Comic Sans", 30, "italic")
turtle.write("Trabalho", False, "center", font1)
turtle.forward(40)
 
font2 = ("Comic Sans", 20, "italic")
turtle.write("de", False, "center", font2)
turtle.forward(45)
 
font3 = ("Comic Sans", 30, "italic")
turtle.write("Informatica", False, "center", font3)
turtle.forward(50)
font4 = ("Comic Sans", 20, "bold")
turtle.write("Currico:", False, "center", font4)
turtle.forward(30)
font5 = ("Comic Sans", 20, "normal")
turtle.write("Victor", False, "center", font5)
turtle.forward(40)
font6 = ("Comic Sans", 20, "bold")
turtle.write("Qualities e Experiencia", False, "center", font6)
turtle.forward(40)
font7 = ("Comic Sans", 20, "normal")
turtle.write("-ele é bom em codicos de tipo html e css, em montar e desmontar Pc. Ainda no primeiro ano de curso", False, "center", font7)
turtle.forward(40)
font8 = ("Comic Sans", 20, "bold")
turtle.write("Atualmente se formando em:", False, "center", font8)
turtle.forward(40)
font9 = ("Comic Sans", 20, "normal")
turtle.write("-Tecnologia da formatação", False, "center", font9)
turtle.forward(40)
turtle.bgcolor("#B0E0E6")
 
input()